name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Enter tag name to be created'
        required: true
      # release_name:
      #   description: 'Enter the release branch name'
      #   required: true
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.tag_name }}
          # body: |
          #   Changelog:
          #   - Added new feature
          #   - Fixed bugs
          draft: false
          prerelease: false
    
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ github.TOKEN }}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          output-file: false
          version-file: .github/package.yaml
          create-summary: true

  release:
    name: Release
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release Notes
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.TOKEN }}
          tag_name: ${{ github.event.inputs.tag_name }}
          prerelease: false
          draft: false
          # files: bin/*
          generate_release_notes: true
          name: ${{ github.ref }}
          body: |
            <details>
              <summary>🤖 Autogenerated Conventional Changelog</summary>

            ${{ needs.changelog.outputs.clean_changelog }}
            </details>







