name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Enter tag name to be created'
        required: true
      # release_name:
      #   description: 'Enter the release branch name'
      #   required: true
        
# jobs:
#   example-job:
#     runs-on: ubuntu-latest
#     steps:
#     # - name: versiontag.sh
#     #   run: |
#     #     chmod +x ./versiontag.sh
#     #     ./versiontag.sh
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Print the version number
#       run: echo "Version number is ${{ github.event.inputs.version }}"
#     - name: Print the release number
#       run: echo "Release number is ${{ github.event.inputs.release_branch }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.tag_name }}
          body: |
            Changelog:
            - Added new feature
            - Fixed bugs
          draft: false
          prerelease: false
      - name: "Complex Configuration"
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/build_changelog@{latest-release}
        with:
          # configuration: "configuration_complex.json"
          # owner: "rpancham"
          # repo: "automate-release"
          ignorePreReleases: "false"
          fromTag: "v0.11.1.6"
          toTag: "v0.11.1.7"
          token: ${{ secrets.TOKEN }}
  
