name: Force push most recent commit to trigger openshift-ci to rebuild images
on:
  workflow_dispatch:
    inputs:
      downstream_repo:
        description: 'Select downstream Repository'
        required: true
        type: choice
        options:
          - 'openvinotoolkit/model_server'
          - 'kserve/kserve'
          - 'kserve/modelmesh'
          - 'caikit-tgis-serving'
          - 'openvinotoolkit/openvino'
          - 'vllm-project/vllm'
          - 'caikit/caikit-nlp'
          - 'caikit/caikit'
          - 'odh-model-controller'
          - 'caikit/caikit-tgis-backend'
          - 'caikit-nlp-client'
          - 'kubeflow/model-registry'
      downstream_branch:
        description: 'downstream_branch branch to Force-push the amended commit'
        required: true

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  create-upstream-pr:
    runs-on: ubuntu-latest
    outputs: 
        upstream_repo: ${{ steps.set-repo.outputs.upstream_org_repo }}
        midstream_repo: ${{ steps.set-repo.outputs.downstream_org_repo }}
    steps:
    - name: Set repository
      id: set-repo
      run: |
        if [[ "${{ github.event.inputs.upstream_repo }}" == *"/"* ]]; then
          IFS='/' read -r upstreamOwner repoName <<< "${{ github.event.inputs.upstream_repo }}"
        else
          repoName=${{ github.event.inputs.upstream_repo }}
          upstreamOwner=""
        fi
        if [ -n "$upstreamOwner" ] && [[ "${{ github.event.inputs.sync_repo }}" == "Upstream->Midstream(opendatahub-io)" ]]; then
          echo "upstream_org_repo=${{ github.event.inputs.upstream_repo }}"  >> $GITHUB_OUTPUT
          # echo "target_org_repo=opendatahub-io/$repoName" >> $GITHUB_OUTPUT
          echo "target_org_repo=rpancham/$repoName" >> $GITHUB_OUTPUT
        else
          echo "upstream_org_repo=opendatahub-io/$repoName"  >> $GITHUB_OUTPUT
          # echo "target_org_repo=red-hat-data-services/$repoName" >> $GITHUB_OUTPUT
          echo "target_org_repo=rpancham/$repoName" >> $GITHUB_OUTPUT
        fi
    - name: Configure Git & install hub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.set-repo.outputs.downstream_org_repo }}
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}

    - name: Amend the last commit & Force-push the amended commit
      run: |
        git commit --amend --no-edit
        git push --force origin ${{ github.event.inputs.downstream_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
