name: Pull from Upstream

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'Select Upstream Repository'
        required: true
        type: choice
        options:
          - 'openvino_model_server'
          - 'kserve'
          - 'modelmesh'
          - 'caikit-tgis-serving'
          - 'openvino'
          - 'vllm'
      upstream_branch:
        description: 'Upstream branch to pull from'
        required: true
      target_branch:
        description: 'Target branch to pull into'
        required: true

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Set repository
      id: set-repo
      run: |
        echo "UPSTREAM_ORG_REPO=opendatahub-io/${{ github.event.inputs.upstream_repo }}" >> $GITHUB_ENV
        echo "MIDSTREAM_ORG_REPO=red-hat-data-services/${{ github.event.inputs.upstream_repo }}" >> $GITHUB_ENV
    - name: Ser git config
      run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
    - name: sync
      uses: TobKed/github-forks-sync-action@master
      with:
        github_token: ${{ github.TOKEN}}
        upstream_repository: opendatahub-io/kserve
        target_repository: test-opendatahub-io/kserve
        upstream_branch: ${{ github.event.inputs.upstream_branch }}
        target_branch: ${{ github.event.inputs.target_branch }}
        force: false
        tags: false
