name: Pull from Upstream and Cherry-pick Patches

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'Select Upstream Repository'
        required: true
        type: choice
        options:
          - 'openvino_model_server'
          - 'kserve'
          - 'modelmesh'
          - 'caikit-tgis-serving'
          - 'openvino'
          - 'vllm'
          - 'caikit-nlp'
          - 'caikit'
          - 'odh-model-controller'
          - 'caikit-tgis-backend'
          - 'caikit-nlp-client'
          - 'model-registry'
      upstream_branch:
        description: 'Upstream branch to pull from'
        required: true
      target_branch:
        description: 'Target branch to pull into'
        required: true
      patch_commits:
        description: 'Comma-separated list of commit SHAs to cherry-pick'
        required: true
      pr_title:
        description: 'Title for the PR'
        required: false
      pr_body:
        description: 'Body for the PR'
        required: false

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  pull_and_cherry_pick:
    runs-on: ubuntu-latest
    outputs: 
        upstream_repo: ${{ steps.set-repo.outputs.upstream_org_repo }}
        midstream_repo: ${{ steps.set-repo.outputs.midstream_org_repo }}
    env:
      BASE_UPSTREAM_URL: https://github.com/opendatahub-io/
      # BASE_TARGET_URL: https://github.com/red-hat-data-services/
      BASE_TARGET_URL: https://github.com/rpancham/
  

    steps:
    - name: Set repository
      id: set-repo
      run: |
        echo "upstream_org_repo=opendatahub-io/${{ github.event.inputs.upstream_repo }}" >> $GITHUB_OUTPUT
        echo "midstream_org_repo=rpancham/${{ github.event.inputs.upstream_repo }}" >> $GITHUB_OUTPUT

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    - name: Checkout temp repo
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.set-repo.outputs.midstream_org_repo }}
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        # path: temp_repo

    - name: Add upstream repository
      run: |
        git remote add upstream ${{ env.BASE_UPSTREAM_URL }}${{ github.event.inputs.upstream_repo }}.git
        git fetch upstream

    - name: Create temporary branch from midstream
      run: |
        git checkout -b cherry-pick-${{ github.event.inputs.patch_commits }}

    - name: Cherry-pick patches
      run: |
        commits="${{ github.event.inputs.patch_commits }}"
         IFS=',' read -ra commit_array <<< "$commits"
          for commit in "${commit_array[@]}"; do
            if git show --no-patch --format=%P $commit | grep -q ' '; then
              echo "Cherry-picking merge commit $commit"
              git cherry-pick -m 1 "$commit" || (git cherry-pick --abort && exit 1)
            else
              echo "Cherry-picking regular commit $commit"
              git cherry-pick "$commit" || (git cherry-pick --abort && exit 1)
            fi
          done

    - name: Push changes to temporary branch 
      run: |
        git status
        git log -n 1 --pretty=format:"%H - %s"
        git push -f origin cherry-pick-${{ github.event.inputs.patch_commits }}
        hub pull-request -b ${{ github.event.inputs.target_branch }} -h cherry-pick-${{ github.event.inputs.patch_commits }} -m "${{ github.event.inputs.pr_title }}\n\n${{ github.event.inputs.pr_body }}"
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_UPSTREAM_TOKEN }}

        
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v6
    #   with:
    #     token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
    #     commit-message: "Cherry-picked commit ${{ github.event.inputs.patch_commits }}"
    #     branch: cherry-pick-${{ github.event.inputs.patch_commits }}  # The branch with the cherry-picked commit
    #     base: ${{ github.event.inputs.target_branch }}
    #     title: "${{ github.event.inputs.pr_title }}  Cherry-picked commit ${{ github.event.inputs.patch_commits }}"
    #     body: |
    #       ${{ github.event.inputs.pr_body }}
    #       This pull request cherry-picks commit ${{ github.event.inputs.patch_commits }}.
    #       - Please review the changes.
