name: Pull from Upstream

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'Select Upstream Repository'
        required: true
        type: choice
        options:
          - 'openvino_model_server'
          - 'kserve'
          - 'modelmesh'
          - 'caikit-tgis-serving'
          - 'openvino'
          - 'vllm'
      upstream_branch:
        description: 'Upstream branch to pull from'
        required: true
      target_branch:
        description: 'Target branch to pull into'
        required: true

jobs:
  pull:
    runs-on: ubuntu-latest
    env:
      BASE_UPSTREAM_URL: https://github.com/opendatahub-io/
      BASE_TARGET_URL: https://github.com/red-hat-data-services/

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.target_branch }}

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Add upstream remote
      run: |
        UPSTREAM_REPO="${{ github.event.inputs.upstream_repo }}"
        UPSTREAM_URL="${{ env.BASE_UPSTREAM_URL }}${UPSTREAM_REPO}.git"
        git remote add upstream $UPSTREAM_URL

    - name: Fetch upstream branch
      run: |
        UPSTREAM_BRANCH=${{ github.event.inputs.upstream_branch }}
        git fetch upstream $UPSTREAM_BRANCH

    - name: Pull from upstream
      run: |
        UPSTREAM_BRANCH=${{ github.event.inputs.upstream_branch }}
        git pull upstream $UPSTREAM_BRANCH
      
    - name: Push changes to target branch
      run: |
        git push origin ${{ github.event.inputs.target_branch }}
